export type Restaurant = {
  id: number; name: string; english: string; halal: 'Halal' | 'Not Halal' | 'Halal shops only';
  photos?: {src:string;alt:string}[];
  budget: string; tags: string[]; meal?: boolean; snack?: boolean;
  dishes: string; description: string; tip: string; address: string; searchName?: string;
};
export const restaurants: Restaurant[] = [
 {id:1,name:'老白家水盆羊肉',english:'Lao Bai Jia Shuipen Lamb',halal:'Halal',budget:'¥30–50 / person',tags:['Lamb'],meal:true,dishes:'Shuipen Lamb · Shuipen Beef · Baiji Bread',description:'A traditional Shaanxi lamb soup, served with baiji bread and pickled garlic.',tip:'A great choice for breakfast or lunch, and an easy introduction to Xi’an’s traditional lamb dishes.',address:'北广济街76号'},
 {id:2,name:'清真盛志望麻酱酿皮铺（大皮院总店）',english:'Sheng Zhi Wang Sesame Liangpi',halal:'Halal',budget:'¥10–30 / person',tags:['Snacks'],snack:true,dishes:'Sesame Liangpi · Spicy Liangpi · Beef Roujiamo',description:'Chewy cold noodles dressed in rich sesame sauce: a classic Xi’an street snack.',tip:'Perfect for a quick stop while exploring the Muslim Quarter. You do not need to make this a full meal.',address:'大皮院西口225号'},
 {id:3,name:'清真东南亚甑糕',english:'Southeast Asia Zenggao',halal:'Halal',budget:'¥10–20 / person',tags:['Sweets'],snack:true,dishes:'Zenggao',description:'A soft, sweet steamed sticky-rice cake layered with dates and beans.',tip:'Best as a snack. Eat it warm if possible.',address:'北广济街129号'},
 {id:4,name:'回民街烤肉 · 马波烤肉',english:'Muslim Quarter BBQ · Ma Bo BBQ',halal:'Halal shops only',budget:'¥30–60 / person',tags:['BBQ'],dishes:'Lamb Skewers · Beef Skewers · Grilled Meat Tendon · Grilled Bread',description:'Explore the Muslim Quarter’s BBQ shops, choosing only those clearly marked 清真. Ma Bo BBQ is our featured stop; navigation opens this shop.',tip:'Ma Bo often has a queue of 1 hour or more at busy times. If you are in a hurry, choose another busy shop clearly marked 清真 nearby.',address:'小学习巷北巷54号',searchName:'马波烤肉'},
 {id:5,name:'同盛祥泡馍（钟楼店）',english:'Tong Sheng Xiang Paomo',halal:'Halal',budget:'¥40–70 / person',tags:['Lamb','Paomo'],meal:true,dishes:'Lamb Paomo · Beef Paomo',description:'One of Xi’an’s classic dishes: small pieces of bread simmered in a rich lamb or beef broth.',tip:'Part of the traditional experience is breaking the bread into small pieces yourself before the soup is added.',address:'西大街5号'},
 {id:6,name:'军军绿豆糕',english:'Junjun Mung Bean Cake',halal:'Halal',budget:'¥20–40',tags:['Sweets'],snack:true,dishes:'Mung Bean Cake',description:'A delicate mung bean sweet to enjoy while exploring, or take back to your hotel as a small local gift.',tip:'A small sweet stop rather than a destination meal.',address:'光辉巷与北大街辅路交叉口西北约40米'},
 {id:7,photos:[{src:'/images/xian-food-map/fumiao-01.jpg',alt:'Fumiao BBQ collage of grilled skewers and side dishes'},{src:'/images/xian-food-map/fumiao-02.jpg',alt:'Fumiao BBQ collage of soups and sweet dishes'},{src:'/images/xian-food-map/fumiao-03.jpg',alt:'A spread of dishes and the interior at Fumiao BBQ'},{src:'/images/xian-food-map/fumiao-04.jpg',alt:'Seasoned grilled meat with vegetables at Fumiao BBQ'}],name:'福苗小骆驼烧烤（莲湖路店）',english:'Fumiao Xiao Luotuo BBQ',halal:'Not Halal',budget:'¥60–80 / person',tags:['BBQ'],dishes:'Grilled Lamb · Beef · Meat Tendon · Grilled Bread',description:'A local BBQ chain popular for grilled meats and relaxed evening meals.',tip:'A reliable local BBQ option when you prefer a sit-down meal to queuing for a famous small shop.',address:'莲湖区莲湖路55号'},
 {id:8,name:'尚寨燎扎咧面馆（钟楼店）',searchName:'尚寨嫽扎咧面馆（钟楼店）',english:'Shangzhai Liaozalie Noodles',halal:'Not Halal',budget:'¥20–40 / person',tags:['Noodles'],dishes:'Youpo Mian · Shaanxi Handmade Noodles',description:'Handmade noodles topped with chilli, spring onions and seasoning, brought to life with sizzling hot oil.',tip:'A good introduction to Shaanxi noodles. Show the staff “少辣，谢谢。” for less spice.',address:'碑林区兴正元广场D座（钟楼地铁站F口步行360米）'},
 {id:9,name:'长安大牌档之上元灯会（钟楼店）',english:'Chang’an Da Pai Dang – Shangyuan Lantern Festival',halal:'Not Halal',budget:'¥50–100 / person',tags:['Shaanxi Cuisine'],meal:true,dishes:'Shaanxi Local Dishes · Biangbiang Noodles · Local Snacks',description:'A sit-down restaurant offering a broad introduction to Shaanxi cooking, beyond a single street snack.',tip:'Choose this for a comfortable full dinner and a variety of local dishes to share.',address:'南大街39号森源大厦1–2层'},
 {id:10,name:'育辉砂锅（西一路店）',english:'Yuhui Clay Pot',halal:'Not Halal',budget:'¥20–40 / person',tags:['Comfort Food'],meal:true,dishes:'Xi’an-style Clay Pot',description:'A warm, everyday clay-pot meal that offers a taste of local life in Xi’an.',tip:'Try this when you want something simple, warm and very local. Especially nice on a cool or rainy day.',address:'西一路191号'},
 {id:11,name:'清真·老毛手抓·非遗（含光路店）',english:'Lao Mao Hand-Grasped Lamb',halal:'Halal',budget:'Around ¥95 / person',tags:['Lamb'],meal:true,dishes:'Hand-Grasped Lamb · Northwest-style Lamb Dishes',description:'A sit-down choice for a hearty Northwest-style lamb meal.',tip:'A good option for a proper lamb dinner. This branch is farther from the central Muslim Quarter; plan your journey before leaving.',address:'含光路南段262号'},
 {id:12,name:'子午路张记肉夹馍（翠华路店）',english:'Ziwu Road Zhangji Roujiamo · Cuihua Road',halal:'Not Halal',budget:'¥15–30 / person',tags:['Roujiamo'],snack:true,dishes:'Traditional Baiji Bread Roujiamo · Liangpi · Meatball Soup',description:'Try classic Xi’an roujiamo: slow-braised pork tucked into traditional baiji bread (白吉馍). The bread has a lightly crisp crust and a firm, chewy centre that soaks up the savoury meat juices.',tip:'Come for the traditional baiji bread roujiamo and enjoy it while warm. Add liangpi or a bowl of soup if you would like a fuller meal.',address:'翠华南路229号挚友大厦一楼'},
 {id:13,name:'陕拾参（北院门创始店）',searchName:'陕拾叁-西安糕点（北院门创始店）',english:'Shaanxi Thirteen · Beiyuanmen Original Store',halal:'Not Halal',budget:'Around ¥20–40 / person',tags:['Ice Cream','Sweets'],snack:true,dishes:'Local-flavour Ice Cream · Qin Su Pastries',description:'A Xi’an dessert stop serving ice cream in locally inspired flavours and Qin Su pastries filled with dates and nuts.',tip:'Choose an ice cream for a sweet break, or pick up pastries to take away. Ask which flavours are available before ordering.',address:'莲湖区北院门270号'},
 {id:14,name:'清真老贾家馄饨',english:'Halal Lao Jia Jia Wontons',halal:'Halal',budget:'Check current menu prices',tags:['Wontons','Comfort Food'],meal:true,dishes:'Beef Wontons in Broth',description:'A local wonton shop serving hand-wrapped beef wontons in a savoury broth. A warm, simple meal while exploring the neighbourhood.',tip:'Choose the Damaishi Street branch at No. 96. Show staff “少辣，谢谢。” if you prefer less chilli.',address:'莲湖区大麦市街96号'},
 {id:15,name:'西安饭庄（东大街店）',searchName:'西安饭庄·非遗（东大街总店）',english:'Xi’an Restaurant · East Street',halal:'Not Halal',budget:'Around ¥100–150 / person',tags:['Shaanxi Cuisine'],meal:true,dishes:'Hulu Chicken · Shaanxi Regional Dishes',description:'A long-established Shaanxi restaurant for a sit-down meal. Its signature hulu chicken has a crisp exterior and tender meat.',tip:'A good choice for sharing several Shaanxi dishes. Check portion sizes with staff when ordering for a small group.',address:'东大街298号'},
];
export const choices = [
 {label:'I want lamb',ids:[1,11,5]}, {label:'I want BBQ',ids:[4,7]},
 {label:'I want noodles',ids:[8]}, {label:'I want local snacks',ids:[2,3,6,12]},
 {label:'I want a full dinner',ids:[9,11]}, {label:'I want something very local',ids:[10]},
];
export function navigationLinks(r: Restaurant) {
 const query = `西安市 ${r.searchName || r.name} ${r.address}`;
 return {amap:`https://uri.amap.com/search?${new URLSearchParams({keyword:query,city:'西安',view:'map',src:'XiaoyaoTravel',callnative:'1'})}`,apple:`https://maps.apple.com/?${new URLSearchParams({q:query})}`};
}
