export type AttractionImageAttribution = {
  id: string;
  nameZh: string;
  nameEn: string;
  file: string;
  imageSrc: string;
  author: string;
  license: string;
  licenseUrl: string;
  sourcePage: string;
  sourcePageLabel: string;
  credit: string;
  modification: string;
};

export const attractionImageAttributions: AttractionImageAttribution[] = [
  {
    id: "city-wall",
    nameZh: "西安明城墙",
    nameEn: "Xi'an City Wall",
    file: "city-wall.webp",
    imageSrc: "/images/attractions/city-wall.webp",
    author: "H2v5o68z",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourcePage: "https://commons.wikimedia.org/wiki/File:City_wall_of_Xi%27an.jpg",
    sourcePageLabel: "City wall of Xi'an.jpg",
    credit: "图片：H2v5o68z / Wikimedia Commons（CC0 1.0）",
    modification: "已按 5:3 居中裁切并转换为 WebP（1600×960，质量 82）。CC0 作品可自由使用和修改。",
  },
  {
    id: "terracotta",
    nameZh: "秦始皇兵马俑博物馆",
    nameEn: "Terracotta Army Museum",
    file: "terracotta.webp",
    imageSrc: "/images/attractions/terracotta.webp",
    author: "xiquinhosilva",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Terracotta_Army_(54083015445).jpg",
    sourcePageLabel: "Terracotta Army (54083015445).jpg",
    credit: "图片：xiquinhosilva / Wikimedia Commons，CC BY 2.0；已裁切并转换为 WebP",
    modification: "已按 5:3 居中裁切并转换为 WebP（1600×960，质量 82）。",
  },
  {
    id: "huaqing",
    nameZh: "华清宫",
    nameEn: "Huaqing Palace",
    file: "huaqing.webp",
    imageSrc: "/images/attractions/huaqing.webp",
    author: "CEphoto, Uwe Aranas",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Lintong_Xian_China_Huaqing-Pool-01.jpg",
    sourcePageLabel: "Lintong Xian China Huaqing-Pool-01.jpg",
    credit: "Photo by CEphoto, Uwe Aranas / Wikimedia Commons，CC BY-SA 3.0；已裁切并转换为 WebP",
    modification: "已按 5:3 居中裁切并转换为 WebP（1600×960，质量 82）。改编版本继续按 CC BY-SA 3.0 发布。",
  },
  {
    id: "huashan",
    nameZh: "西岳华山",
    nameEn: "Mount Hua",
    file: "huashan.webp",
    imageSrc: "/images/attractions/huashan.webp",
    author: "chensiyuan",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourcePage: "https://commons.wikimedia.org/wiki/File:1_mount_hua_shan_china_2011.jpg",
    sourcePageLabel: "1 mount hua shan china 2011.jpg",
    credit: "图片：chensiyuan / Wikimedia Commons，CC BY-SA 3.0；已裁切并转换为 WebP",
    modification: "已从画面中部按 5:3 裁切并转换为 WebP（1600×960，质量 82），保留主要山峰、山脊和险峻地貌。改编版本继续按 CC BY-SA 3.0 发布。",
  },
  {
    id: "everbright-city",
    nameZh: "大唐不夜城",
    nameEn: "Great Tang All Day Mall",
    file: "everbright-city.webp",
    imageSrc: "/images/attractions/everbright-city.webp",
    author: "源義信",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourcePage:
      "https://commons.wikimedia.org/wiki/File:2023-10-10_%E8%A5%BF%E5%AE%89%E5%A4%A7%E5%94%90%E4%B8%8D%E5%A4%9C%E5%9F%8E_Great_Tang_All_Day_Mall_05.jpg",
    sourcePageLabel: "2023-10-10 西安大唐不夜城 Great Tang All Day Mall 05.jpg",
    credit: "图片：源義信 / Wikimedia Commons，CC BY 4.0；已裁切并转换为 WebP",
    modification: "已按 5:3 居中裁切并转换为 WebP（1600×960，质量 82）。",
  },
  {
    id: "shaanxi-history",
    nameZh: "陕西历史博物馆",
    nameEn: "Shaanxi History Museum",
    file: "shaanxi-history.webp",
    imageSrc: "/images/attractions/shaanxi-history.webp",
    author: "Wang Zhongyin",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Shaanxi_History_Museum.jpg",
    sourcePageLabel: "Shaanxi History Museum.jpg",
    credit: "图片：Wang Zhongyin / Wikimedia Commons，CC BY-SA 4.0；已裁切并转换为 WebP",
    modification: "已按 5:3 居中裁切并转换为 WebP（1600×960，质量 82）。改编版本继续按 CC BY-SA 4.0 发布。",
  },
  {
    id: "hukou",
    nameZh: "黄河壶口瀑布（陕西侧）",
    nameEn: "Hukou Waterfall (Shaanxi)",
    file: "hukou.webp",
    imageSrc: "/images/attractions/hukou.webp",
    author: "Leruswing",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Hukou_Waterfall.jpg",
    sourcePageLabel: "Hukou Waterfall.jpg",
    credit: "图片：Leruswing / Wikimedia Commons，CC BY-SA 3.0；已裁切并转换为 WebP",
    modification: "已按 5:3 居中裁切并转换为 WebP（1600×960，质量 82），画面主体为黄河瀑布水流。改编版本继续按 CC BY-SA 3.0 发布。",
  },
  {
    id: "baota-mountain",
    nameZh: "宝塔山",
    nameEn: "Baota Mountain",
    file: "baota-mountain.webp",
    imageSrc: "/images/attractions/baota-mountain.webp",
    author: "Sunatnight",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourcePage: "https://commons.wikimedia.org/wiki/File:%E5%BB%B6%E5%AE%89%E5%AE%9D%E5%A1%94%E5%A4%9C%E6%99%AF.png",
    sourcePageLabel: "延安宝塔夜景.png",
    credit: "图片：Sunatnight / Wikimedia Commons，CC BY-SA 3.0；已裁切并转换为 WebP",
    modification: "已按 5:3 居中裁切并转换为 WebP（1600×960，质量 82）。改编版本继续按 CC BY-SA 3.0 发布。",
  },
  {
    id: "henan-longmen-grottoes",
    nameZh: "龙门石窟",
    nameEn: "Longmen Grottoes",
    file: "henan-longmen-grottoes.webp",
    imageSrc: "/images/attractions/henan-longmen-grottoes.webp",
    author: "Tgasrio",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Luoyang_longmen_grottoes.jpg",
    sourcePageLabel: "Luoyang longmen grottoes.jpg",
    credit: "图片：Tgasrio / Wikimedia Commons（CC0 1.0）",
    modification: "已按 5:3 居中裁切并转换为 WebP（1600×960，质量 82）。CC0 作品可自由使用和修改。",
  },
  {
    id: "henan-shaolin-temple",
    nameZh: "少林寺",
    nameEn: "Shaolin Temple",
    file: "henan-shaolin-temple.webp",
    imageSrc: "/images/attractions/henan-shaolin-temple.webp",
    author: "tak.wing",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Shaolin_temple_entrance.jpg",
    sourcePageLabel: "Shaolin temple entrance.jpg",
    credit: "图片：tak.wing / Wikimedia Commons，CC BY-SA 2.0；已裁切并转换为 WebP",
    modification: "已按 5:3 居中裁切并转换为 WebP（1600×960，质量 82）。改编版本继续按 CC BY-SA 2.0 发布。",
  },
  {
    id: "henan-qingming-park",
    nameZh: "清明上河园",
    nameEn: "Millennium City Park",
    file: "henan-qingming-park.webp",
    imageSrc: "/images/attractions/henan-qingming-park.webp",
    author: "Gary Todd",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourcePage: "https://commons.wikimedia.org/wiki/File:2014_Millennium_City_Park_with_Kaifeng_in_Background.jpg",
    sourcePageLabel: "2014 Millennium City Park with Kaifeng in Background.jpg",
    credit: "图片：Gary Todd / Wikimedia Commons（CC0 1.0）",
    modification: "已按 5:3 居中裁切并转换为 WebP（1600×960，质量 82）。CC0 作品可自由使用和修改。",
  },
  {
    id: "henan-laojun-mountain",
    nameZh: "老君山",
    nameEn: "Laojun Mountain",
    file: "henan-laojun-mountain.webp",
    imageSrc: "/images/attractions/henan-laojun-mountain.webp",
    author: "Huangdan2060",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Laojun_Mountain_18_March_2025F.jpg",
    sourcePageLabel: "Laojun Mountain 18 March 2025F.jpg",
    credit: "图片：Huangdan2060 / Wikimedia Commons，CC BY 4.0；已裁切并转换为 WebP",
    modification: "已按 5:3 居中裁切并转换为 WebP（1600×960，质量 82）。",
  },
];
