export const zhContact = {
  eyebrow: "联系",
  title: "联系我们",
  description:
    "请发送您的目的地、团型、出行日期、人数及核心需求，我们将为您提供线路建议、产品方案与落地执行支持。",
  channelsEyebrow: "渠道",
  channelsTitle: "联系方式",
  channelsDescription: "选择最便于您团队沟通的渠道与我们联系。",
  formEyebrow: "需求",
  formTitle: "提交合作需求",
  formDescription: "请填写以下信息，我们将尽快与您联系。（当前为静态表单，后续可对接邮件或 CRM。）",
  formNote: "您也可复制需求内容，通过 WhatsApp、邮箱、微信或小红书直接联系我们。",
  fields: [
    { label: "姓名", name: "name", placeholder: "您的姓名" },
    { label: "公司 / 机构", name: "company", placeholder: "公司或机构名称" },
    { label: "国家 / 地区", name: "region", placeholder: "国家 / 地区" },
    { label: "联系方式", name: "contactMethod", placeholder: "邮箱 / WhatsApp / 微信" },
    {
      label: "目的地",
      name: "destination",
      placeholder: "陕西 / 黑龙江 / 河南 / 吉林 / 多城市",
    },
    {
      label: "团型",
      name: "groupType",
      placeholder: "入境团 / 研学 / 企业会奖 / 邮轮 / 定制",
    },
    { label: "预计人数", name: "groupSize", placeholder: "例如：40–60 人" },
    { label: "出行时间", name: "dates", placeholder: "例如：2026 年 10 月，6 天 5 晚" },
  ],
  messageLabel: "需求说明",
  messagePlaceholder:
    "团型特点、行程重点、酒店标准、必游项目、预算范围及其他约束条件。",
  submitCta: "提交需求",
  whatsappAction: "WhatsApp 联系",
  emailAction: "发送邮件",
  wechatLabel: "微信",
  wechatAlt: "逍遥旅游微信二维码",
  xiaohongshuLabel: "小红书",
  xiaohongshuAlt: "逍遥旅游小红书二维码",
  tapToEnlarge: "点击放大",
  whatsappDescription: "发送团型、目的地、出行日期与人数等核心信息。",
  emailDescription: "发送详细需求与希望回复的方式。",
} as const;
